---
title: "Quantifying the Uncertainty of GHG extensions in MRIO"
format: html

---


## Description

This is the main script. 
It runs the individual R scripts in the required order

## Packages

```{r}
library(data.table)
library(tidyverse)
library(units)
library(ggforce)

library(countrycode)
library(data.tree)
library(callr)
library(job)
```





## Execute Scripts

### Create Correspondence Table

```{r}
rscript('0a_create_CT_CRF_classification.R')
```

### Prepare Data

```{r}
rscript('1a_prepare_UNFCCC_CRF.R')
```

```{r}
rscript('1b_prepare_UNFCCC_uncertainty.R')
```


```{r}
rscript('1c_repair_CRF_categories.R')
```


### Sample GHG extensions

#### UNFCCC

```{r}
rscript('2a_merge_CRF_NIR_data.R')
```

```{r}
rscript('2b_sample_UNFCCC.R')
```


#### Edgar


```{r}
rscript('3a_parse_EDGAR_emissions.R')
```

```{r}
rscript('3b_parse_EDGAR_uncertainty.R')
```

```{r}
rscript('3c_sample_EDGAR.R')
```


#### Residence Adjustment

```{r}
rscript('4a_residence_adjustment_SEA_prepare_data.R')
```

```{r}
rscript('4b_residence_adjustment_SEA_sample.R')
```


```{r}
rscript('4c_residence_adjustment_AIR_prepare.R')
```

```{r}
rscript('4d_residence_adjustment_AIR_sample.R')
```

```{r}
rscript("4e_residence_adjustment_ROAD_prepare.R")
```

here

#### Prepare Proxies 


```{r}
rscript('4a_prepare_SUT_proxies.R')
```


```{r}
rscript('4b_prepare_PEFA_proxies.R')
```



```{r}
rscript('prepare_EMPLOYMENT_proxies.R')
```

```{r}
rscript('prepare_ROAD_TRANSPORT_proxies.R')
```



```{r}
rscript('5a_UNFCCC_get_EXIOBASE_proxies.R')
```

```{r}
rscript('6a_EDGAR_get_proxies.R')
```


#### Sample Extensions

```{r}
rscript("7_combine_UNFCCC_EDGAR_samples.R")
```

```{r}
rscript("4f_residence_adjustment_ROAD_sample.R")
```

```{r}
rscript("7b_run_optimizer.R")
```

```{r}
rscript("5c_sample_EXIOBASE.R")
```


```{r}
rscript("prepare_EXIOBASE_samples.R")
```



```{r}
rscript("5d_convert_to_matrix.R")
```

```{r}
rscript("prepare_EXIOBASE.R")
```


### Calculate Footprints (national/industry)

```{r}
rscript('6_calculate_footprints.R')
```


### Analyse results

```{r}
rscript('7a_analyse_extensions.R')
```



